README.md
Creation and first draft of the readme
closes #1
=> Create readme 1

portfolio.md
* Qu'est-ce que cette PR va changer ?
Ajouter le portfolio.md
* Pourquoi l'a-t-on changé ?
Le portfolio est nécessaire au projet
* Comment l'a-t-on testé ?
Pas de test nécessaire
* Est-ce que cette feature va encore évoluer ?
Evidemment, tout au long du projet
Closes #11
=> Add portfolio file

code-of-conduct.md
Une fois appliqué ce commit permettra d'avoir un code de conduite en français.
=> traduction en français

pom.xml, src/main/java/Statique.java, src/main/java/commands/Version.java, src/main/resources/project.properties, src/test/java/commands/VersionTest.java
closes #26 #17 
Une fois appliqué ce commit ajoutera au programme la possibilité d'afficher sa version.
Pour utiliser cette fonctionnalité il faut ajouter -version lors de l'appel du programme
=> ajoute l'option -version qui affiche la version du programme

src/main/java/commands/Init.java, src/main/resources/index.md, src/test/java/commands/InitTest.java
Closes #30 
J'ai ajouté pour l'instant l'implémentation de la commande init à partir d'un path. Ca créé le dossier en fonction du path donné en argument et ça copie un template  md vers le dossier créé, selon les conventions dont on avait discuté.
~~Il faut encore que j'écrive quelques tests, mais j'ouvre déjà la PR~~
EDIT: J'ai ajouté quelques tests
=> Feature init

.github/workflows/maven.yml, pom.xml
~Pour vérifier que ce fichier de config fonctionne bien, nous devons le merge dans la branche main et regarder si les testes sont effectuée sur les PR faites sur la branche main.~
closes #29
~Pour ce qui est du formatage du code, il faut discuter car le code actuel n'est pas bien formaté on peut imaginer un commit qui fera le formatage de l'ancien code 
Êtes-vous ok avec ceci ?~
Discuté en privé et va être réglé par #43 
@Lollipoke @magskwa @vogelma
=> Ajout de l'intégration continue (build + testes + lint)

src/main/resources/index.md
Closes #46 
Fix le mauvais format de index.md
=> Corriger index.md

.github/workflows/maven.yml
closes #50
ça devrait fixer le problème de la dépendance manquante dans le pipeline de cicd
=> ajout de la dépendance pandoc qui manquait

README.md
=> documente l'installation et l'utilisation du programme

portfolio.md
Cette PR va mettre à jour le portfolio afin d'ajouter les informations concernant le Sprint 1.
Close #37
=> Mettre à jour le portfolio

src/main/java/commands/Clean.java, src/test/java/commands/CleanTest.java
Implémentation de la commande clean grâce à picocli
close #27 
close #20
=> Feature commande clean

src/main/java/commands/Build.java
=> correction de l'erreur pour l'exécution de la commande pandoc

README.md
Cette pr ajoute de la documentation à jour pour #67 et #74 
Le temps pris est de 30 minutes
=> Documentation des commandes

portfolio.md
Le portfolio est mis à jour d'après les commentaires reçus en classe pour le sprint 1.
Un chapitre sur le sprint 2 sera écrit pour résumer ce qui a été fait et ce qui doit encore être fait.
=> Créer un fil rouge des informations à ajouter pour le sprint 2

src/main/java/commands/Serve.java, src/test/java/commands/ServeTest.java
Le temps total de travail est d'environ 4h
Cette pull request ajoute la commande serve. Elle close #62 
La commande serve se passe de la manière suivante désormais :
Après avoir init et build, on peut désormais serve pour créer un serveur qui affiche la page html créée
Cette pull request est accompagné de tests.
=> Feature commande serve

src/main/java/commands/Clean.java
Le temps total de travail est d'environ 1h
Cette pull request corrige la commande clean. Elle close #77 
La commande clean supprime maintenant bien le dossier build comme attendu.
=> Fix le bug de clean qui ne supprimait pas le dossier build

src/main/java/Statique.java, src/main/java/commands/Build.java, src/main/java/commands/Serve.java, src/main/java/interfaces/Subject.java, src/main/java/utils/Watcher.java, src/test/java/utils/WatcherTest.java
- Temps passé 2h
- Qu'est-ce que cette PR va changer ?
Elle ajout l'opportunité de faire la compilation à la volée du site
- Pourquoi l'a-t-on changé ?
feature demandée
- Comment l'a-t-on testé ?
On a testé le watch service, et vérifié que le callable était bien appelé 
- Est-ce que cette feature va encore évoluer ?
Oui puisque il faut maintenant modifier les commandes pour accepter l'option --watch
Closes #81
=> Ajout de la compilation à la volée

portfolio.md
* Temps passé 40min
*   Qu'est-ce que cette PR va changer ?
Elle ajoute des détails sur le temps passé sur le projet
* Pourquoi l'a-t-on changé ?
Pour tenir à jour notre rapport.
* Est-ce que cette feature va encore évoluer ?
Oui, le portfolio va encore changer pour être plus détaillé.
=> Ajout d'un tableau de comparaison de temps dans le portfolio

src/main/java/commands/Build.java
- Temps passé 15'
- Qu'est-ce que cette PR va changer ?
Elle ne change pas le comportement, cependant elle offre un gain de ~30% lors de la compilation d'un site en sortant une allocation couteuse hors d'une boucle.
- Pourquoi l'a-t-on changé ?
Afin de gagner en performance ! 
- Comment l'a-t-on testé ?
Avec les testes habituelles, aucune feature n'ayant été ajoutée
- Est-ce que cette feature va encore évoluer ?
link #101 #93 #87
=> Optimise le processus de build

.github/workflows/maven.yml
- Qu'est-ce que cette PR va changer ?
Elle fait en sorte que la cicd run sur plusieurs os(linux, macos et windows)
- Pourquoi l'a-t-on changé ?
Seul linux était testé
- Comment l'a-t-on testé ?
on verra si les testes passe sur cette branche
- Est-ce que cette feature va encore évoluer ?
non car on souhaite pas supporter d'autre os que les principaux.
temps estimé 10' 
il n'y a pas de story liée
=> Ajout des tests sur macos et sur windows
